### ISSUE TITLE
PLEASE, HELP!

### ISSUE THREAD

**Issue by OwWEN** [DarkStorm652/DarkBot#30]
When I try to join a server i have:
[vvmapmcwpqljkvl] Done! (1)
java.io.EOFException
        at java.io.DataInputStream.readInt(Unknown Source)
        at org.darkstorm.darkbot.minecraftbot.protocol.AbstractProtocol.readHead
er(Unknown Source)
        at org.darkstorm.darkbot.minecraftbot.protocol.SocketConnectionHandler$R
eadTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[vvmapmcwpqljkvl] Disconnected: Read error: java.io.EOFException

**Comment by Unihedro** [comment]
Not sure what help you're trying to get here. This is a known issue. The way to fix is to join a server with the proper protocol.

**Comment by OwWEN** [comment]
thanks, now working
