### ISSUE TITLE
EOFException

### ISSUE THREAD

**Issue by z3ntu** [DarkStorm652/DarkBot#38]
When I try to run DarkBot I get the following error message and I don't know how to solve it / interpret it^^

```
C:\Users\Luca\DarkBot\DarkBotMaster>java -jar DarkBot.jar -t bot -o Mike_Dillon
-u <my email address> -p <my password> -s 127.0.0.1
[JackDawn] YggdrasilSession{username=JackDawn,password=<my password>,accessToken=<some random letters>,clientToken=<more letters>,selectedProfile=YggdrasilSession.Profile{id=<again more letters>,name=JackDawn},availableProfiles=[YggdrasilSession.Profile{id=<and some letters the last time>,name=JackDawn}]}
java.io.EOFException
        at java.io.DataInputStream.readInt(Unknown Source)
        at org.darkstorm.darkbot.minecraftbot.protocol.AbstractProtocol.readHeader(Unknown Source)
        at org.darkstorm.darkbot.minecraftbot.protocol.SocketConnectionHandler$ReadTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[JackDawn] Disconnected: Read error: java.io.EOFException
```

EDIT: I have a localhost server with version 1.7.9 vanilla running where I try to connect to.

**Comment by TheBiblMan** [comment]
fix it then

**Comment by DarkStorm652** [comment]
The communication link falls apart when on the wrong 1.7 protocol for some reason. Try specifying --protocol 5 or --protocol 4

**Comment by z3ntu** [comment]
Which one is 5 and which is 4? :D

**Comment by z3ntu** [comment]
Ok THANK YOU for helping me! --protocol 5 worked for a 1.7.9 Server :) Keep up the work :+1:
