### ISSUE TITLE
Disconnected: Read error: java.io.EOFException

### ISSUE THREAD

**Issue by OXAYAZA** [DarkStorm652/DarkBot#58]
I can not connect to any server:
[ATOM] Disconnected: Read error: java.io.EOFException
java.io.EOFException
    at java.io.DataInputStream.readInt(Unknown Source)
    at org.darkstorm.darkbot.minecraftbot.protocol.AbstractProtocol.readHeader(AbstractProtocol.java:43)
    at org.darkstorm.darkbot.minecraftbot.protocol.SocketConnectionHandler$ReadTask.run(SocketConnectionHandler.java:263)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

On the server:
java.io.IOExeption: Bad packet id 84
    at ey.a(SourceFile:185)
    at co.i(SourceFile:249)
    at co.c(SourceFile:17)
    at cp.run(SourceFile:94)
Disconnecting /127.0.0.1:52799: Protocol error
/127.0.0.1:52799 lost connection

Startup line:
java -jar DarkBot.jar --type bot --protocol 78 --offline  --username ATOM --owner OXAYAZA --server localhost:25565

**Comment by Ac3W0lfJ3rk** [comment]
try another protocol, but it isnt working for 1.8

**Comment by vakkq** [comment]
Wrong protocol leaves a different error.
https://docs.oracle.com/javase/7/docs/api/java/io/EOFException.html
