### ISSUE TITLE
No support for protocol v338

### ISSUE THREAD

**Issue by vakkq** [DarkStorm652/DarkBot#63]
```
[Bot] Error connecting: org.darkstorm.darkbot.minecraftbot.protocol.UnsupportedProtocolException: No protocol support for v338 found.
org.darkstorm.darkbot.minecraftbot.protocol.UnsupportedProtocolException: No protocol support for v338 found.
        at org.darkstorm.darkbot.minecraftbot.MinecraftBot.<init>(Unknown Source)
        at org.darkstorm.darkbot.minecraftbot.MinecraftBot.<init>(Unknown Source)
        at org.darkstorm.darkbot.minecraftbot.MinecraftBot$Builder.build(Unknown Source)
        at org.darkstorm.darkbot.mcwrapper.cli.CLIBotWrapper.createBot(Unknown Source)
        at org.darkstorm.darkbot.mcwrapper.cli.CLIBotWrapper.main(Unknown Source)
        at org.darkstorm.darkbot.mcwrapper.Main.main(Unknown Source)
```

**Comment by vakkq** [comment]
My name is Stanley Kenway, and I'm necroing over here!

**Comment by DarkStorm652** [comment]
Protocol system is being rewritten for another project and will be ported over here. Progress is looking good. Additionally, the development-cleanup branch contains many new features that you can test on 1.7.x, like simple physics.

**Comment by vakkq** [comment]
How can we know when it's finished?

**Comment by ghost** [comment]
You only know when the code has updated. Untill then, theres nothing to do but wait!

**Comment by vakkq** [comment]
How to import the Gradle project? i'm stuck in eclipse ;-;
I'm of course talking about the dev branch.

**Comment by vakkq** [comment]
Going off topic here, but after compiling it with "gradle build", i cannot run it because
`no main manifest attribute, in DarkBotDev3.jar`

**Comment by DarkStorm652** [comment]
The Gradle scripts replacing the old Ant scripts are crappy at best and have many issues. The most effective thing you can do right now is the following:

1. Run `gradle build`
2. Remove the `META-INF` folder from `core/build/libs/core-all.jar` (due to signing issues)
3. Run `java -cp "core/build/libs/core-all.jar:protocol/build/libs/DarkBot.jar" org.darkstorm.minecraft.darkbot.wrapper.Main <args>` (replace : with ; on Windows)

Additionally, importing the project (via existing sources, build.gradle) in IntelliJ and setting up a run configuration for `org.darkstorm.minecraft.darkbot.wrapper.Main` with your arguments _should_ work out of the box, but you know how that usually goes 😒 

I hope to find some time to make the project more presentable in the near future. 1.8+ support comes first, though.

**Comment by vakkq** [comment]
```
java.lang.ClassNotFoundException: 5
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.darkstorm.minecraft.darkbot.wrapper.cli.CLIWrapperUtils.getProtocolProvider(CLIWrapperUtils.java:59)
	at org.darkstorm.minecraft.darkbot.wrapper.cli.CLISpamBotWrapper.main(CLISpamBotWrapper.java:246)
	at org.darkstorm.minecraft.darkbot.wrapper.Main.main(Main.java:47)
No protocol provider found for '5'.
```
It also says that I need a protocol name
I typed --protocols and it seems that there are none, so I copied all protocols from the regular version.
Idk where to copy it to, the error is still present.

**Comment by vakkq** [comment]
Also why am i getting EOFExceptions on the old version

**Comment by DarkStorm652** [comment]
The protocol loader uses the Java SPI system for discovering protocols, which won't work without the protocols being specially packaged. That packaging is one of the most important things missing from the new build scripts. You can specify a protocol class explicitly instead: `--protocol 'org.darkstorm.minecraft.darkbot.protocol.v5x.Protocol5X$Provider'`.

There will be sporadic EOFExceptions on connection due to a race condition bug in the networking code, probably related to encryption, that I never took the time to fix. They only happen during the initial handshaking and logging in steps of connecting to a server.

**Comment by undercoverGuy** [comment]
Is minecraft 1.8 and up supported with the new (protocolsystem)-version?

**Comment by vakkq** [comment]
No, minecraft 1.8 protocol is under development.

**Comment by undercoverGuy** [comment]
any updates?

**Comment by undercoverGuy** [comment]
guess not

**Comment by lol7344** [comment]
> guess not

Lol I've been waiting years for him to update this bot... :( There's a pretty good API I found tho, it's named mineflayer and if you know just a little of JavaScript you can do pretty good things with it
