### ISSUE TITLE
java.lang.NullPointerException on Connecting

### ISSUE THREAD

**Issue by mcmdev** [DarkStorm652/DarkBot#64]
Here is the full Exception:
java.lang.NullPointerException
        at org.darkstorm.darkbot.minecraftbot.MinecraftBot.<init>(Unknown Source)
        at org.darkstorm.darkbot.minecraftbot.MinecraftBot.<init>(Unknown Source)
        at org.darkstorm.darkbot.minecraftbot.MinecraftBot$Builder.build(Unknown Source)
        at org.darkstorm.darkbot.mcwrapper.cli.CLIBotWrapper.createBot(Unknown Source)
        at org.darkstorm.darkbot.mcwrapper.cli.CLIBotWrapper.main(Unknown Source)
        at org.darkstorm.darkbot.mcwrapper.Main.main(Unknown Source)
Exception in thread "main" java.lang.NullPointerException
        at org.darkstorm.darkbot.mcwrapper.cli.CLIBotWrapper.main(Unknown Source)
        at org.darkstorm.darkbot.mcwrapper.Main.main(Unknown Source)

My Command Line: java -jar DarkBot.jar -t bot -u chrisvasti@sbcglobal.net -p ... -s testedsky.bukkit.eu -o atomicnitro5

**Comment by mcmdev** [comment]
Fixed.
